# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://nghung123.github.io"
baseurl: "/moonrise"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2020
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: RiluxSMP
serverDescription: Nơi mọi thứ được bắt đầu!.
serverIP: riluxsmp.relox.tech
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/D8aCkQDveE
discordServerID: 938759756624039948
discordChannelID: 938788645937233931


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Map máy chủ
#     url: map
#     newtab: true
#   - name: Cấu hình
#     url: screenshots
#   - name: Thông tin
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
